[project]
name = "ee596-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "ipython>=9.7.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "seaborn>=0.13.2",
    "torch==2.2.2",
    "torchvision==0.17.2",
    "torchaudio==2.2.2",
    "torchtext==0.17.2",
    "ipykernel>=7.1.0",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true
